# Generated by Django 5.1.7 on 2025-04-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="td_chat_id",
            field=models.CharField(blank=True, null=True, unique=True, verbose_name="Телеграм"),
        ),
    ]
