# Generated by Django 5.1.7 on 2025-03-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(blank=True, max_length=100, null=True, verbose_name="Место")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Время")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("sign_pleasant_habit", models.BooleanField(default=False)),
                ("periodicity", models.IntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                (
                    "complete_time",
                    models.IntegerField(blank=True, null=True, verbose_name="Время выполнения (в секундах)"),
                ),
                ("publicity_sign", models.BooleanField(default=False)),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="habits.habit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
