# Generated by Django 5.1.7 on 2025-03-26 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(max_length=1000, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)],
            ),
        ),
    ]
